"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider, QueryClient, useQuery } from "react-query";
import Navbar from "@/components/Navbar";
import BgVideo from "@/components/BgVideo";
import { useAtom } from "jotai";
import { climate } from "./atom";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const [src, setSrc] = useAtom(climate);
  return (
    <html lang="en" className="dark">
      <QueryClientProvider client={queryClient}>
        <body className={`${inter.className} h-screen overflow-hidden`}>
          <Navbar />
          {children}
          <BgVideo src={src} />
        </body>
      </QueryClientProvider>
    </html>
  );
}
